
public class Conf {
	public static int readerBufferSize = 1024 * 1024;
	public static String initialURL = "https://appexchange.salesforce.com/";
	public static String outputPath = "C:\\Users\\Neu\\Desktop";
	public static String uRLsCachePath = Conf.outputPath + "\\urls.csv";

	public static String file = "result.csv";
	public static int maxScrapingThreads = 8;
	public static boolean appURLsCached = true;
	/**
	 * Make sure this folder exists in advance.
	 */
	public static String reviewsFolderPath = "\\revs\\";
	public static String XPATH_APPS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV[2]/DIV/DIV/SPAN[2]/SPAN/UL/LI/SPAN/DIV[1]/DIV[1]/DIV[1]/DIV[3]/DIV[1]/A";
//	caution:It points to more than one ANCHOR:
	public static String XPATH_NEXT_PAGE_BUTTON = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV[3]/DIV/DIV/DIV/A";	
	public static String XPATH_APP_NAME = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/SPAN/DIV/DIV/DIV/DIV/H1";
	public static String XPATH_SUBTITLE = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/SPAN/DIV/DIV/DIV/DIV/P";
	public static String XPATH_REVIEW_NUMBER = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/SPAN/DIV/DIV/DIV/DIV/SPAN/P";
	public static String XPATH_INTRO = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV/SPAN/DIV/DIV/DIV/P[2]/SPAN";
	public static String XPATH_RELEASE_DATE = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV/SPAN/DIV/DIV/DIV[2]/SPAN/P";
	public static String XPATH_PRICING = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV/SPAN/DIV/DIV/DIV[2]/SPAN[2]/STRONG/SPAN";
	public static String XPATH_CATEGORIES = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV/SPAN/DIV/DIV/DIV[2]/SPAN[3]/SPAN/P";
	public static String XPATH_PRODUCER = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV/SPAN/DIV/DIV/DIV/P/B";
	public static String XPATH_DETAIL_TAB = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV/DIV/UL/LI[2]/A";
	public static String XPATH_DETAILS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[2]/SPAN/DIV/DIV/DIV";
	public static String XPATH_WEBSITE_OR_EMAIL = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[2]/SPAN/DIV[2]/DIV/DIV/DIV/DIV/P/A";
	public static String XPATH_SALES_PHONE = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[2]/SPAN/DIV[2]/DIV/DIV/DIV/DIV/P/SPAN/SPAN";
	public static String XPATH_SALESFORCE_EDITIONS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[2]/SPAN/DIV[2]/DIV/SPAN/DIV/DIV[2]/DIV/UL/LI";
	public static String XPATH_TECH_DETAILS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[2]/SPAN/DIV[2]/DIV/DIV[2]/DIV/DIV/UL";
	public static String XPATH_SUPPORTED_FEATURES = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[2]/SPAN/DIV[2]/DIV/DIV[2]/SPAN/DIV";
	public static String XPATH_PROVIDER_TAB = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV/DIV/UL/LI[4]/A";
	public static String XPATH_SOMEWHERE_IN_PROVIDER_TAB = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[4]/SPAN/DIV[2]/DIV/SPAN/DIV/DIV/DIV/P/SPAN";
	public static String XPATH_ABOUT_PROVIDER = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[4]/SPAN/DIV[2]/DIV/SPAN/DIV/DIV/DIV/P";
	public static String XPATH_PROVIDER_DETAILS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[4]/SPAN/DIV/DIV";
	public static String XPATH_PROVIDER_DETAILS_INNER = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[4]/SPAN/DIV/DIV/DIV";
	public static String XPATH_REVIEWS_TAB = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV/DIV/UL/LI[3]/A";
	public static String XPATH_SOMEWHERE_IN_REVIEWS_TAB = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/SPAN[2]/DIV[2]/DIV/H5";
	public static String XPATH_RATING_AVERAGE = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/DIV[2]/DIV/SPAN/SPAN/DIV/DIV/DIV[1]";
	public static String XPATH_5STARS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/DIV[2]/DIV/SPAN/SPAN/DIV[2]/DIV/DIV[1]";
	public static String XPATH_4STARS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/DIV[2]/DIV/SPAN/SPAN/DIV[2]/DIV/DIV[2]";
	public static String XPATH_3STARS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/DIV[2]/DIV/SPAN/SPAN/DIV[2]/DIV/DIV[3]";
	public static String XPATH_2STARS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/DIV[2]/DIV/SPAN/SPAN/DIV[2]/DIV/DIV[4]";
	public static String XPATH_1STARS = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/DIV[2]/DIV/SPAN/SPAN/DIV[2]/DIV/DIV[5]";
	public static String XPATH_RATING = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/SPAN[2]/DIV[3]/DIV/SPAN/DIV/DIV/DIV/SPAN[2]/SPAN/P/SPAN";
	public static String XPATH_REVIEW = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/SPAN[2]/DIV[3]/DIV/SPAN";
	public static String RELATIVE_XPATH_REVIEW_EXTENDED_CONTENT = "/DIV/DIV/DIV/SPAN[3]/SPAN[2]";
	public static String XPATH_NEXT_REVIEW_PAGE_BUTTON = "/HTML/BODY/DIV/DIV/DIV/DIV/DIV/DIV/FORM/DIV/DIV[2]/DIV/DIV[3]/SPAN/SPAN[2]/SPAN/DIV/DIV/DIV/SPAN/A";

}
